# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
skipsdist = true
envlist = terraform-integration
minversion = 4.0

[testenv:terraform-integration]
description = Run Terraform integration tests with pytest + jubilant
package = skip
setenv =
    PYTHONPATH = {toxinidir}
passenv =
    HOME
    PATH
    TERM
    CI
    JUJU_*
    TF_*
    HTTPS_PROXY
    HTTP_PROXY
    NO_PROXY
deps =
    pytest
    jubilant~=1.0
    pyyaml
commands =
    pytest -v --tb native --log-cli-level=INFO -s tests/integration/terraform {posargs}
